### PR TITLE
upgrade loom version

### PR DESCRIPTION
**Pull request by psandana**
I had a transitive issue with dependencies. As this crate depends on `loom`, I need to upgrade `loom` version to consume latest version of the dependencies :)

### CODE REVIEW

**Comment by sbarral** [comment]
Thanks for that!
But it's a bit surprising to me that a `dev-dependency` would affect your crate, especially that it should only be active if you set the `diatomic_waker_loom` flag.

**Comment by sbarral** [comment]
Published in v0.2.1.

**Comment by psandana** [comment]
`loom` is not a `dev-dependency` on `diatomic-waker` crate:

```toml
[target.'cfg(diatomic_waker_loom)'.dependencies]
waker-fn = "1.1"
loom = "0.7"
```
As you may see here, it is a normal `dependency` that happens to appear when the `cfg` flag is present. But to my understanding, `cargo` still will look this as a normal `dependency` as it has no way to determine if the compilation flag will be present or not beforehand. You can see `loom` listed in the dependencies for `diatomic-waker` in crates.io:

https://crates.io/crates/diatomic-waker/0.2.1/dependencies
image

For the record, the first thing I tried was to move `loom` to `dev-dependencies`, but I noticed that you will require to add `loom` as a dependency to let other projects to test `diatomic-waker` with `loom`. If you don't like this behavior, then it is possible to change the `cfg` flag to an optional feature, with will make `loom` and `waker_fn` as optional dependencies. Here is an example:

https://github.com/asynchronics/diatomic-waker/pull/8

**Comment by sbarral** [comment]
Oh yes, you are right, it's a regular dependency. I wasn't aware that conflict resolution doesn't account for compilation flags, that's too bad...

**Pull request merged**
