### PR TITLE
loom as dev dependency

### PR DESCRIPTION
**Pull request by psandana**

### CODE REVIEW

**Comment by sbarral** [comment]
Thanks for the PR, but I think I will just accept that there is no real good solution at the moment...

Features should be strictly additive and shouldn't break user code when turned on, which is why I am reluctant to put this behind a feature. So for now let's keep it as a flag, as annoying as it is, until a better solution comes up.
Thanks very much for the effort though.

**Comment by psandana** [comment]
> Features should be strictly additive

Features are recommended to be additive as there is no support for exclusive feature declaration. But it might come some day..... Still, there are cases you cannot go around it and you need exclusive features. To prevent enabling both you can add a mutual check (pseudo-code):

```rust
#[cfg(all(feature = "feature_a", feature = "feature_b"))]
compile_error!("Features 'feature_a' and 'feature_b' cannot be enabled at the same time");
```

I just realized that it might be a 3rd option: `cfg(test)`. The cool thing about `cfg(test)` is that only enable code behind it inside the unit tests of the same crate. Integration tests, or external crates won't have access to code behind `cfg(test)`. And I think with that you can promote `loom` as a `dev-dependency`. Would you like me to try it? :)

**Comment by sbarral** [comment]
It would be ideal if we could just rely on `cfg(test)` indeed. I seem to recall that for some reason I couldn't get this to work, but if you manage then it would be great.

One reason I avoid non-additive features is that in crates that have many features, I prefer to run the CI commands with `all-features` so I don't accidentally forget to test newly-added features. Of course for `diatomic_waker` there is only one feature so it's easy to manage, but I'd like to come up with a general solution that I can reuse for larger crates too.
 
Your PR got me thinking that if all else fails, we could combine the previous approach with this PR: both the `diatomic_waker_loom` flag and a `loom` feature would be needed to run loom tests. The advantage is that when the flag is not set, the `loom` feature does nothing so it is technically additive.

**Comment by psandana** [comment]
Oh, the `dep:<dependency>` is available on Rust 1.60 onwards :/. Would you mind if we move forward the `rust-version`?

**Comment by psandana** [comment]
> Your PR got me thinking that if all else fails, we could combine the previous approach with this PR: both the diatomic_waker_loom flag and a loom feature would be needed to run loom tests. The advantage is that when the flag is not set, the loom feature does nothing so it is technically additive.

I would propose to change the `diatomic_waker_loom` flag with just `cfg(test)`. I think they are both doing the same. Unless you are expecting to run `loom` on integration tests later. If we implemented on this way:
- users of `diatomic-waker` won't be affected (no-op) by enabling the feature ✅
- `loom` is only enabled for unit testing, if the feature is enabled.

I'm assuming you still want to run tests without `loom` and with `loom`. If this is not a requirement, we do not need the feature anymore, and this gets way more simpler.

**Comment by psandana** [comment]
Here is an alternative solution: https://github.com/asynchronics/diatomic-waker/pull/9. Good thing about that, it does not affect external users. Features are additive. Just that in test, if enabled, uses loom :)

**Comment by sbarral** [comment]
> Oh, the `dep:<dependency>` is available on Rust 1.60 onwards :/. Would you mind if we move forward the `rust-version`?

I don't mind, just a small price to pay :)

**Comment by sbarral** [comment]
> I'm assuming you still want to run tests without `loom` and with `loom`. If this is not a requirement, we do not need the feature anymore, and this gets way more simpler.

Yes, this is important because I'd like the solution to keep working if more regular tests are added in the future, so your solution in PR #9 is exactly what I wanted, thanks :)

**Pull request closed without merging**
